services:
  vaguely-rude-places:
    image: sebp/lighttpd
    networks:
      - vicchi-backend
    expose:
      - 80
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
        - ./dist/vaguely-rude-places:/var/www/localhost/htdocs
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaguely-rude-places.rule=Host(`${SITE_HOST:?Site host not defined}`)
      - traefik.http.routers.vaguely-rude-places.entrypoints=websecure
      - traefik.http.routers.vaguely-rude-places.tls.certresolver=reverse-proxy-ssl

networks:
    vicchi-backend:
      external: true